INSERT INTO bookdetails(book_id,book_author,book_genre,book_popularity,book_title) VALUES(6,'na','SF',7,'nimo');
INSERT INTO bookroom(bookroom_id,book_id,theme_color,theme_music_url,user_id) VALUES (8,6,'red','www.a',11);
INSERT INTO favorite(favorite_id, bookroom_id, isfavorite,user_id) VALUES (1,8,3,24);
INSERT INTO friend(friend_id,user_friend_id,user_id) VALUES (13,24,25);
INSERT INTO mindmap(mind_id,bookroom_id,priority,word_picture_url,word_text,word_voice_url) VALUES(15,8,17,'www.b','blue','www.c');
INSERT INTO parent(parent_id,age,created_at,nickname,pw,status,update_at,user_id) VALUES(27,68,current_timestamp,'hong','abc',20,current_timestamp,24);
INSERT INTO picturetable(picture_id,bookroom_id,picture_url) VALUES (41,8,'www.d');
INSERT INTO roomview(bookroom_id,book_id,book_title,character_id,face_color,face_style,gender,head_color,head_style,isfavorite,nickname,pants_color,pants_style,shoes_color,shoes_style,theme_color,theme_music_url,top_color,top_style,user_id)VALUES (8,6,'nimo',38,'b','c','d','e','f',36,'jung','g','h','i','j','green','www.e','k','l',37);
INSERT INTO user(user_id,age,created_at,nickname,phonenumber,profile_color,pw,status,update_at) VALUES (24,25,current_timestamp,'jun','010','pink','def',26,current_timestamp);
INSERT INTO user(user_id,age,created_at,nickname,phonenumber,profile_color,pw,status,update_at) VALUES (25,26,current_timestamp,'jun2','010','pink','ghi',26,current_timestamp);
INSERT INTO user(user_id,age,created_at,nickname,phonenumber,profile_color,pw,status,update_at) VALUES (26,57,current_timestamp,'jun3','010','pink','def',26,current_timestamp);
INSERT INTO usercharacter(character_id,user_id,book_id,gender,nickname,head_style,head_color,top_style,top_color,pants_style,pants_color,shoes_style,shoes_color,face_color,face_style,created_at,updated_at) VALUES (54,24,6,'a','b','c','d','e','f','g','h','i','j','k','l',current_timestamp,current_timestamp);
INSERT INTO wordtable(word_id,bookroom_id,main_id,word_main,word_picture_url,word_text,word_voice_url) VALUES (30,8,32,33,'www,e','black','www.f');